[package]
name = "zecdec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inotify = "0.8.2"
execute = "0.2.12"
chrono = "0.4"
tokio = "1.33.0"
